DROP SCHEMA IF EXISTS `bookstore`;
CREATE SCHEMA IF NOT EXISTS `bookstore`;

DROP TABLE IF EXISTS bookstore.BOOK;
CREATE TABLE IF NOT EXISTS bookstore.BOOK (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255),
    AUTHOR VARCHAR(255),
	PUBLICATION VARCHAR(255),
    PRIMARY KEY (ID)
);

SELECT * FROM bookstore.BOOK;